export const LIST_SCHOOL_TIMETABLE = 'LIST_SCHOOL_TIMETABLE'
export const LIST_GRADE_TIMETABLE = 'LIST_GRADE_TIMETABLE'
export const LIST_TEACHER_TIMETABLE = 'LIST_TEACHER_TIMETABLE'
export const LIST_ACTIVE_SUBJECTS = 'LIST_ACTIVE_SUBJECTS'