export const ADMIN_LIST_SCHOOLS = 'ADMIN_LIST_SCHOOLS'
export const ADMIN_LIST_GRADES = 'ADMIN_LIST_GRADES'
export const ADMIN_LIST_SUBJECTS = 'ADMIN_LIST_SUBJECTS'
export const ADMIN_LIST_PERMISSIONS = 'ADMIN_LIST_PERMISSIONS'