export const LIST_GRADES_MASTER = 'LIST_GRADES_MASTER'
export const LIST_ACADEMIC_YEAR_MASTER = 'LIST_ACADEMIC_YEAR_MASTER'
export const LIST_SCHOOL_TEACHERS_MASTER = 'LIST_SCHOOL_TEACHERS_MASTER'
export const LIST_SUBJECTS_MASTER = 'LIST_SUBJECTS_MASTER'